export const my_projects = [
	{
		name: "Quizzy Quizzes",
		description: "",
		stack: ["ReactJS", "TailwindCSS"],
		link: "",
		img: [],
	},
	{
		name: "To-Do-List",
		description: "",
		stack: ["ReactJS", "TailwindCSS"],
		link: "",
		img: [],
	},
	{
		name: "Magnus eCommerce",
		description: "",
		stack: ["NextJS", "TailwindCSS", "GraphQL", "Strapi"],
		link: "",
		img: [],
	},
	{
		name: "macOS Calculator Clone",
		description: "",
		stack: ["ReactJS", "TailwindCSS"],
		link: "",
		img: [],
	},
	{
		name: "Cine-Cine Movie Booking System",
		description: "",
		stack: ["NextJS", "TailwindCSS", "Firebase", "Chakra"],
		link: "",
		img: [],
	},
	{
		name: "Wordle Clone",
		description: "",
		stack: ["ReactJS", "TypeScript", "TailwindCSS"],
		link: "",
		img: [],
	},
	{
		name: "Migo",
		description: "",
		stack: ["Vite", "TailwindCSS", ".NET Core", "Chakra"],
		link: "",
		img: [],
	},
	{
		name: "Bo Chat App",
		description: "",
		stack: [
			"NextJS",
			"TailwindCSS",
			"Node.js",
			"Express",
			"MongoDB",
			"Socket.io",
		],
		link: "",
		img: [],
	},
];
